### ISSUE TITLE
Enable vim jump behavior with <C-o>/<C-i>

### ISSUE THREAD

**Issue by alonsorivera** [AlexPl292/IdeaVim-EasyMotion#10]
Hi,
It is possible to enable vim jump behavior with `<C-o>/<C-i>` to go back and forward to the previous position before jump? This means the plugin must save the position on vim jump list (`:jumps` command) before the motion. You can see this behavior in the original Vim EasyMotion plugin.

I did it some time ago with AceJumpLite plugin (compiled locally). It was something like that:

```java
//...the code before jump
saveVimJump();
//... more stuff

private void saveVimJump() {
  if (VimPlugin.isEnabled()) {
      VimPlugin.getMark().saveJumpLocation(editor);
  }
}
```

Thanks.

**Comment by AlexPl292** [comment]
Hi! Yes, this question has already been asked here, and we are thinking about a possible solution: https://github.com/acejump/AceJump/issues/312

**Comment by AlexPl292** [comment]
Fixed with v.1.2
