### ISSUE TITLE
map <Leader>n <Plug>(easymotion-bd-wl) doesn't work

### ISSUE THREAD

**Issue by baober90** [AlexPl292/IdeaVim-EasyMotion#104]
when upgrade ideavim to version 2.8.0.
command :   <Plug>(easymotion-bd-wl) can not work

**Comment by Vozf** [comment]
I have also troubles with `ll j` after upgrad

**Comment by baober90** [comment]
upgrade ideavim to version 2.8.1
upgrade ideavim-easymotion to version 1.11
(easymotion-bd-wl) works ok
