### ISSUE TITLE
easymotion-s2 repeats last command [bug]

### ISSUE THREAD

**Issue by jordigraumo** [AlexPl292/IdeaVim-EasyMotion#11]
First of all, thanks for the plugging!

When using <Plug>(easymotion-s2)  and move somewhere on the screen, the  command following the motion, is executed 2 times instead of just 1. Example:

I have the cursor in []

H[e]llo world one two!

then use <Plug>(easymotion-s2) + "or" to move to

Hello w[o]rld one two!

then press "dw" to delete "orld" but instead it deletes "orld one" giving:

Hello wtwo!

Similar behaviour with simple motions: If instead of "dw" I press "w" to move a word:

Hello w[o]rld one two!    --> Hello world one [t]wo!

**Comment by AlexPl292** [comment]
As far as I understand, this issue was fixed by the last refactoring of mappings in IdeaVim code. Feel free to reopen it in case of any additional issues.
