### ISSUE TITLE
Add easymotion's jump to jump list

### ISSUE THREAD

**Issue by arm-liang** [AlexPl292/IdeaVim-EasyMotion#13]
I wonder if it can add Easymotion's jump to the `vim jumplist`, so I can use not only `'.` go back to last jump, but also `<C-o>` `<C-i>`.
It will be very helpful when editing multiple lines.

**Comment by arm-liang** [comment]
So far, at least, Easymotion has broken the original jumplist.

**Comment by AlexPl292** [comment]
Hi! Thank you for the report. The similar issue has already been raised: #10
