### ISSUE TITLE
mapleader with comma doesn't work

### ISSUE THREAD

**Issue by Zeta611** [AlexPl292/IdeaVim-EasyMotion#14]
I have `let mapleader = ','` in my .ideavimrc, and it doesn't seem to be working with it.
When I use the default '\', it works great.
Is this a bug, or am I missing something?

**Comment by AlexPl292** [comment]
Hi! Do you have a declaration of `mapleader` before the usages of `<leader>`?
Could you also try to use `let mapleader = ","`?

**Comment by Zeta611** [comment]
`let mapleader = ","` works like charm! Why does it work with double quotation marks but not with single quotes?

**Comment by AlexPl292** [comment]
Well, because the guy who programmed the parsed for IdeaVim didn't handle a single quotes case or something like that :)
I've filed an issue: https://youtrack.jetbrains.com/issue/VIM-1914
