### ISSUE TITLE
leader +w problem

### ISSUE THREAD

**Issue by amazingXiong** [AlexPl292/IdeaVim-EasyMotion#15]
![image](https://user-images.githubusercontent.com/48853137/71766275-26ded300-2f39-11ea-8be5-c080c0d6603d.png)

when i input `'<leader>' + w`
I want to the `RT`, but it have `r` and `t` ,if i input `r` and `t` ,cursor go to the `t` position.

**Comment by Zeta611** [comment]
Does mapping leader to other than `\` works at all, e.g., `let mapleader = ","`?

**Comment by AlexPl292** [comment]
Hi! Thank you for the report. This is a known issue: https://github.com/acejump/AceJump/issues/310
