### ISSUE TITLE
Still doesn't understand how it works

### ISSUE THREAD

**Issue by Oliveiras** [AlexPl292/IdeaVim-EasyMotion#16]
I've installed IdeaVim + AceJump + IdeaVim-EasyMotion, as requested in the Setup section of the Readme.

I have `<leader>` mapped to `<space>` ( `let mapleader=' '` ). But when I press `<space><space>f` or `<space><space>w` nothing happens.

I have tried to map it to another key ( `nmap \ <Plug>(easymotion-w)` ), but still nothing happens.

Here is some lines from the output of my :map command:

        <Plug>(easymotion-e) * call org.jetbrains.plugins.StandardHandler
        <Plug>(easymotion-f) * call org.jetbrains.plugins.StandardHandler
        <Plug>(easymotion-w) * call org.jetbrains.plugins.StandardHandler
     n  \             <Plug>(easymotion-w)

How can I map this commands to any key?

**Comment by AlexPl292** [comment]
Hi! Could you please attach the log file? https://intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files

**Comment by oemergenc** [comment]
Hi, i am facing exactly the same problem. I installed all plugin, inserted `set easymotion` in .ideavimrc, restarted ide, but somehow the ideavim-easymotion bindings do not work. Any progress on this?

The acejump plugin works by using the configuration mentioned here:
https://github.com/acejump/AceJump#configuring

However ideavim-easymotion bindings do not work?

**Comment by alexxbb** [comment]
Same situation here, AceJump CTRL+; works, but this plugin seems like doesn't.

**Comment by AlexPl292** [comment]
@alexxbb since the `.ideavimrc` reads the file top-down, the initialization of easymotion happens before the command `set mapleader = ","`. Could you please put the `mapleader` command before the `set easymotion`?

**Comment by AlexPl292** [comment]
@oemergenc sorry for the late answer. Doesn't [this](https://github.com/AlexPl292/IdeaVim-EasyMotion/issues/16#issuecomment-576558104) answer help you?

**Comment by oemergenc** [comment]
@AlexPl292 thank you very much, yes indeed, this solves the problem. Very nice, i was waiting a long time  to use easymotion in ideavim.

**Comment by AlexPl292** [comment]
@Oliveiras any updates on this issue?

**Comment by Oliveiras** [comment]
[idea.log](https://github.com/AlexPl292/IdeaVim-EasyMotion/files/4122845/idea.log)

Sorry for late response.

I've attached the log file of today.
There some stacktraces on it. I think it may be helpful.

**Comment by AlexPl292** [comment]
The stacktraces look a bit strange. Seems like your plugin installations are somehow corrupted. Could you please reinstall the plugins and try again?

**Comment by xiexingguang** [comment]
I aslo meet the same  problem , IdeaVim + AceJump + IdeaVim-EasyMotion all been installed.but it seems no work!!
my .ideavimrc file like this:
 let mapleader=","
 source ~/.vimrc
 set easymotion

**Comment by zsolt-donca** [comment]
I also can't get this plugin work. I am on IntelliJ IDEA 2020.1 with the latest versions of the plugins.

**Comment by AlexPl292** [comment]
@xiexingguang could you please try to remove `source ~/.vimrc`? IdeaVim has pretty simple vimscript parser which may be broken by complicated `.vimrc`.

Could you please attach the log and the content of `~/.ideavimrc`?

I'm closing this particular issue. If anybody has a similar problem, please create a new ticket.
