### ISSUE TITLE
Region you jump over gets selected

### ISSUE THREAD

**Issue by prasant94** [AlexPl292/IdeaVim-EasyMotion#24]
When I jump from point A to point B, all the text between those two points gets selected. Then I need to hit Esc to unselect before I can go into insert mode to type something. I'm not sure if this is a bug or if there's an option to disable this.

**Comment by AlexPl292** [comment]
It definitely shouldn't act like this. Are you sure you don't hold `Shift` during the jump or you are not in the visual mode before the jump? How do you perform jumping?

**Comment by prasant94** [comment]
Wow ok. Sorry, it's my bad. The jump labels are upper case so I've been holding `Shift` while I press the keys for jumping.
