### ISSUE TITLE
Include Manual Installation Instructions in Readme

### ISSUE THREAD

**Issue by johngkhs** [AlexPl292/IdeaVim-EasyMotion#3]
Hi,

Would you be able to include the steps required to build the plugin from scratch from the command line? I tried ./gradlew buildPlugin, but I am missing the dependencies and I'm not familiar with the build process. The error is "Cannot use project ':acejump' as a plugin dependency. IntelliJ Plugin is not found."

Thanks.

**Comment by AlexPl292** [comment]
Hi!
The plugin has currently "in progress" state as mentioned in the description above. If you really like to test it, you need do clone IdeaVim and [this](https://github.com/acejump/AceJump/pull/307) pull request of AceJump into the IdeaVim-EasyMotion folder, fix all the shown gradle warnings (it mostly consist of removing library versions and highlighted script blocks) and call `./gradlew buildPlugin`.
