### ISSUE TITLE
how to disable all default mapping of this plugins?

### ISSUE THREAD

**Issue by could-be** [AlexPl292/IdeaVim-EasyMotion#31]
how to disable all default mapping of this plugins?
I want only define those mappings that i need?
how to disable the defaulting mapping?
Is there a autocmd group idsable mapping that work for it?

**Comment by AlexPl292** [comment]
The plugin supports some of the original [options](https://github.com/AlexPl292/IdeaVim-EasyMotion#supported-options).
Please use `let g:EasyMotion_do_mapping=0`.
