### ISSUE TITLE
How can I remap (easymotion-f)?

### ISSUE THREAD

**Issue by drericrobinson** [AlexPl292/IdeaVim-EasyMotion#32]
I'd like to remap `f` to run `(easymotion-f)` instead of using `<leader><leader>f`.

How can I do that?

I tried:
```
set easymotion
nmap f <Plug>(easymotion-f)
```

But that doesn't work.

**Comment by AlexPl292** [comment]
Hi! The config seems fine for me. Do you have anything else in the `~/.ideavimrc`? Could you please also attach the log (https://intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files)?
