### ISSUE TITLE
Not working `Ctrl + [` as `Esc`

### ISSUE THREAD

**Issue by Ganariya** [AlexPl292/IdeaVim-EasyMotion#33]
Hello!

```c++
int main() {

    // here is a cursor.

    return 0;
}

```

If a cursor is there such that up example, and I press `\\f`then, easymotion can't find any characters, so I have to `Ctrl + [` or `Esc`.

However, `Ctrl+[` doesn't work and , I have to press `Esc` in distance.

How should I do, or is it some problem in source code?

Thank you!

**Comment by AlexPl292** [comment]
Hi! Why do you need to press `Esc`? Are you trying to start easymotion from insert mode?
Could you maybe please attach a small screencast?

**Comment by Ganariya** [comment]
Hello, @AlexPl292 !
Thank you for replying!

If I press `\ \ f 0`, the image below.

![](https://i.gyazo.com/3064e5278c0334764be5b703e6aa725a.gif)


However, I press`\ \ f 2`, the image below.

![](https://i.gyazo.com/b06a22ff2aa38725c0bc8a3fe81fc3c9.gif)

`f` commands try to find `2`, however, there is no `2`, so easymotion stops behaviour.
And, If I press `Ctrl + [ ( As Esc)` , cannot finish easymotion. 
Of course, If I press `Esc`, then easymotion finishs, but I would like to finish easymotion by `Ctrl + [` because Esc is so far from home position on keyboard.


Sorry, for vague description...
Thank you!

**Comment by AlexPl292** [comment]
Aha, I see! Yep, this is a bug, thank you for the report.
