### ISSUE TITLE
possibility to implement vim sneak ?

### ISSUE THREAD

**Issue by xiaoouwang** [AlexPl292/IdeaVim-EasyMotion#34]
vim easymotion is good at large-scale jump but sometimes I don't want to choose one among many options and just go to the first match.

In Vim I really like vim sneak plugin.  Basically it just go to the first 2 character match. And moreover it's repeatable with ; and , !

Is it possible to implement it in ideavim easymotion ? Really interesting it would be !

Tks for this amazing plugin

**Comment by AlexPl292** [comment]
Hi! IdeaVim has a feature request for this plugin. You can track it's status here: https://youtrack.jetbrains.com/issue/VIM-1915
