### ISSUE TITLE
what's the default leader key?

### ISSUE THREAD

**Issue by huahuayu** [AlexPl292/IdeaVim-EasyMotion#35]
hi, I am new to easymotion, I never used it before in vim, but in vscode, I happened found when I press space, I get options to jump to, I think the function is called easymotion, because when I press space there's a word `EASYMOTION` comes to the bottom line.

So I search for the plugin in jetbrains, I use vim plugin in jetbrains. I want the same trick in jetbrains.

I have IdeaVim, AceJump, IdeaVim-EasyMotion installed.

The problem is, after install your plugin, when press space, the behavior is different from vscode. I don't know how to use it. 

So what's your IdeaVim-EasyMotion default leader key, readme doesn't say. 

If you give more guidelines that will be appreciated.

**Comment by AlexPl292** [comment]
Hey, the default leader key in vim and IdeaVim is `\`. You can remap it to space using `let mapleader=" "` in `~/.ideavimrc` file. Also, don't forget that you should add `set easymotion` to the same file.

**Comment by rohitkrishna094** [comment]
I was about to type this question as well. In my intellj I type backslash then I type a character that I want to go to, but its not working. I am new to vim, do I need to type leader twice? I tried that as well, but its not working either. Sorry this might sound like a stupid question, do you know exactly what characters I need to type to let easymotion to work?

I am doing this now:

\L

where L is the character I want to go to(i.e., there is a variable Long and I want to go to Long).

**Comment by huahuayu** [comment]
@AlexPl292 
I have all the three plugins installed and enabled, and `set easymotion` added to `~/.ideavimrc`  

restart webstorm 2020.1

![image](https://user-images.githubusercontent.com/1725060/81470530-c7ae0980-921d-11ea-8e9f-effb14d23a35.png)

**the problem:**
1. `\` key is not working
2. remap it to space using let mapleader=" " in ~/.ideavimrc also not working, press space key the cursor just go right same as `->` key

**Comment by AlexPl292** [comment]
@huahuayu the leader key should be pressed twice. So, if you want, for example, jump to character `x` you should enter `\\fx`.
If it won't work for you, could you please attach log file? https://intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files

@rohitkrishna094 could you please attach the log file (see the link above)

**Comment by huahuayu** [comment]
hi, @AlexPl292 finally I get to know how to use, `\\f` is the trick. I just tried, it works, great!

In retrospect, before you tell me to use `\\f[keyword]`I think two things made me confused, 1. which is the leader key? 2. I don't know the leader key `\` should press twice, AND followed by an `f`.

Could you please add them to the document, make other people's life a little bit easier :)

**Comment by AlexPl292** [comment]
Yes, definitely. Thank you very much for the issue, it made me understanding that the documentation should be improved.

**Comment by huahuayu** [comment]
Thank you for your support! I read the document again, there's actually a key list. But unfortunately, I can't understand in the first place.

I suggest a short use a video (with [keycastr](https://github.com/keycastr/keycastr) will be even better)  or gif animation to demonstrate the feature will be good.

**Comment by rohitkrishna094** [comment]
@AlexPl292 Idk what happened, but after remapping the leader, it's working now. Thanks.
