### ISSUE TITLE
Cannot map <leader> to <space> Key.

### ISSUE THREAD

**Issue by nkgrnkgr** [AlexPl292/IdeaVim-EasyMotion#36]
I wrote this setting in ideavimrc.
But I cannot map leader to <space> key.

 ~/.ideavimrc
```
let mapleader="\<space>"
set easymotion
```

**Comment by AlexPl292** [comment]
Try to replace `let mapleader="\<space>"` with `let mapleader=" "`

**Comment by nkgrnkgr** [comment]
Thank you!
I could map <leader> to " " Key!
