### ISSUE TITLE
disabling mappings

### ISSUE THREAD

**Issue by mario-mazo** [AlexPl292/IdeaVim-EasyMotion#38]
Hello

in vscode I have <ll> bdw mapped to space
and when it shows lets say HH when I press H then highlights all the Hs and then you type the second H and you move to that word.

Here the behavior is different. 
first <ll> bdw doesnt work and when you have like HH you type the the first H it starts looking for words that start with h and highlight some words are somewhere in the file, the when you type H again it actually goes to where HH initially was.

im guessing is because `<Plug>(easymotion-bd-w) mapped to bd-tn`  so I tried `let g:EasyMotion_do_mapping = 0
` but still not working.

whats the trick to disable the `n` here?

thanks

ideavim
```
let mapleader = ","
set easymotion
let g:EasyMotion_do_mapping = 0
imap jj <Esc>
map  <Space> <Plug>(easymotion-bd-w)
```

**Comment by AlexPl292** [comment]
Hi! Unfortunately, this is an issue in AceJump plugin: https://github.com/acejump/AceJump/issues/310
