### ISSUE TITLE
光标定位有BUG

### ISSUE THREAD

**Issue by installH** [AlexPl292/IdeaVim-EasyMotion#40]
当搜索记录中有SE和E是，输入se会定位到E上

**Comment by AlexPl292** [comment]
Hi! Unfortunately, I don't understand Chinese and my translator gives me senseless translation. Could you please translate your request to English?

**Comment by buyou0821** [comment]
same issue.

![image](https://user-images.githubusercontent.com/37977488/91933672-0f502800-ed1c-11ea-9184-1e9f0df0e6fd.png)
There are `U` and `HU`.When I press `H`. There will be two U. How do I jump to the second U?
