### ISSUE TITLE
single leader mapping does not work for <Plug>(easymotion-s) command

### ISSUE THREAD

**Issue by mgartner** [AlexPl292/IdeaVim-EasyMotion#50]
With a `.ideavimrc` of:

```
" Use comma key as leader
let mapleader = ","

" Use easymotion
set easymotion
map <Leader> <Plug>(easymotion-prefix)
```

When I type `,w` the easymotion plugin executes `<Plug>(easymotion-w)`. But when I type `,s` it does not execute `<Plug>(easymotion-s)`. Oddly, `,,s` does execute `<Plug>(easymotion-s)`.

**Comment by ljohnston** [comment]
There's definitely something weird with regard to the handling of easymotion prefix. 

When doing `set easymotion` in `.ideavimr`, you will get a mapping of `<Leader><Leader> <Plug>(easymotion-prefix)` and a subsequent mapping of any other key to `<Plug>(easymotion-prefix)` does _not_ remove the original mapping. So, in your case, I'd expect if you did a `:map` you'd see both mappings:
```
,  <Plug>(easymotion-prefix)
,, <Plug>(easymotion-prefix)
```
I don't know if that would have any bearing on the behavior you're seeing or not, but maybe?

Furthermore, and this seems like a bug (in ideavim, I'd guess?), if you attempt to unmap the `<Leader><Leader>` mapping in your `.ideavimrc` after applying the easymotion plugin, the unmap is ignored and has no effect. Although once you're in an open editor, `:unmap <Leader><Leader>` _will_ work.

**Comment by AlexPl292** [comment]
Hi folks, I've released a new version of IdeaVim-EasyMotion with several fixes regarding the mappings.
The fact is that if `~/.ideavimrc` contains a mapping to `<Plug>(easymotion-prefix)`, the default mappings should not be created.
Could you please check your use cases? I've tried ot reproduce the issue with `,w` and `,s`/`,,s` mappings, but I'm not sure if I understood you correctly. Is it the full config of your `~/.ideavimrc`? Don't you have any other mappings directrly to `<Plug>(easymotion-w)`?

**Comment by ljohnston** [comment]
Hi @AlexPl292 - Thanks for the new release! Doing some quick testing, looks like this issue is resolved! Thanks again!
