### ISSUE TITLE
Disabling default key mappings does not work

### ISSUE THREAD

**Issue by martindzejky** [AlexPl292/IdeaVim-EasyMotion#52]
Hi! In my `.ideavimrc` I have these settings:

```
let mapleader=" "
set easymotion
let g:EasyMotion_do_mapping=0

" ...

nnoremap <silent> <Leader><Leader> :action GotoAction<CR>
```

and it does not work as expected. Despite the fact that I'm trying to disable easemotion's default bindings with `let g:EasyMotion_do_mapping=0`, it still overrides (and breaks) my `<Leader><Leader` mapping! 😞 

Is this a bug or am I doing something wrong?

**Comment by martindzejky** [comment]
Note that I also tested

```
let mapleader=" "
let g:EasyMotion_do_mapping=0
set easymotion
```

and it does not work either.

**Comment by Jacob3075** [comment]
Same thing happens for me, easy motion <leader><leader> mapping is not removed. But if I

- open by ideavimrc file
- make some changes
- reload ideavimrc

my mapping for <leader><leader> is loaded. Have to do this everytime I open a project.
Currently on IDEA 2021.1 Ultimate

**Comment by Jacob3075** [comment]
As far as I understand this plugin is just a wrapper around your AceJump plugin, so if I disable the easymotion plugin and just manually map the keys my-self will loss any features?

**Comment by ljohnston** [comment]
> Is this a bug or am I doing something wrong?

Seems like a bug.

**Comment by martindzejky** [comment]
> As far as I understand this plugin is just a wrapper around your AceJump plugin, so if I disable the easymotion plugin and just manually map the keys my-self will I loss any features?

@Jacob3075 one important thing you will lose is to map the easymotion action only while in normal mode. 😞

**Comment by Adir-Shemesh** [comment]
Hey! I opened a pull request to solve this a while ago:

https://github.com/AlexPl292/IdeaVim-EasyMotion/pull/72

Until it's approved and merged, my fork can be used

**Comment by martindzejky** [comment]
@Adir-Shemesh that's great, but how can I use your fork in my Webstorm? I don't see any other `IdeaVim-Easemotion` plugin in the marketplace.

**Comment by Adir-Shemesh** [comment]
I didn't upload it to the marketplace, just built it myself and selected the resulting zip in `Plugins > gear icon > install plugin from disk`

If you don't want to build it yourself, here is my zip:
[IdeaVim-EasyMotion-1.6.zip](https://github.com/AlexPl292/IdeaVim-EasyMotion/files/7837996/IdeaVim-EasyMotion-1.6.zip)

**Comment by Adir-Shemesh** [comment]
I have submitted the fork to the marketplace, but it's still pending approval:

https://plugins.jetbrains.com/plugin/18375-ideavim-easymotion-prefix-fork

**Comment by martindzejky** [comment]
@Adir-Shemesh it works!

**Comment by Adir-Shemesh** [comment]
That's awesome to hear! :smile: 
The fork was also approved in the marketplace, so it can be installed from there in the future

**Comment by AlexPl292** [comment]
The fix was merged and will be provided with the next release. Thank you @Adir-Shemesh !
