### ISSUE TITLE
The plugin makes IdeaVim unable to enter normal mode using ESC

### ISSUE THREAD

**Issue by nomanous** [AlexPl292/IdeaVim-EasyMotion#53]
I install this plugin and find that ESC for IdeaVim to switch from insert mode to normal mode doesn't work anymore after the installation. I have done some experiments. Every time I disable this plugin, IdeaVim's function resume, so I think it's this plugin's bug. I use IntelliJ IDEA ~~2021.3.3~~ 2020.3.3 and IdeaVim 0.65.

**Comment by Cosmic-Goat** [comment]
I'm getting the same issue, also using IdeaVim 0.65 and IntelliJ 2020.3.3. (I'm assuming you meant 2020 instead of 2021?)

**Comment by AlexPl292** [comment]
Hi! Please try ot update to the latest version (`1.5`)
