### ISSUE TITLE
`easymotion-sl` can not work as expect after upgrading to 1.5

### ISSUE THREAD

**Issue by g199209** [AlexPl292/IdeaVim-EasyMotion#54]
When I use `easymotion-sl`, I expect to search something in this line. This function works well in EasyMotion 1.4 & AceJump 3.6.3. 

But when I upgrade to  EasyMotion 1.5 & AceJump 3.7 a few days ago, this function can not work.  `easymotion-sl` has the same behavior as `easymotion-s`, which will search the full screen text.

I think this shoud be a bug.

1.4:

![1 4](https://user-images.githubusercontent.com/15379793/113993110-aa971600-9886-11eb-8e83-3999ebcb3d31.png)

1.5:

![1 5](https://user-images.githubusercontent.com/15379793/113993122-af5bca00-9886-11eb-8941-9930ae5f4bdd.png)

`.ideavimrc` related config:

```
; Enable Ideavim extensions
set easymotion
nmap <leader>s <Plug>(easymotion-s)
nmap f <Plug>(easymotion-sl)
```

**Comment by AlexPl292** [comment]
Hi! AceJump did a really big release with a lot of changes and we were not ready for this. The current release (1.5) was done just to fix the compatibility issues and at the moment I am working on restoring the correct functionality.

**Comment by g199209** [comment]
@AlexPl292 Looking forward for your next release :)

**Comment by AlexPl292** [comment]
Hi! Please update to the latest versions of AceJump (3.7.1) and IdeaVim-EasyMotion (1.6).
