### ISSUE TITLE
It doesn't work？！

### ISSUE THREAD

**Issue by xbear23** [AlexPl292/IdeaVim-EasyMotion#7]
I installed AceJump & IdeaVim-EasyMotion and added `set easymotion` to my ~/.ideavimrc，and then nothing happened. It just like normal AceJump。

**Comment by AlexPl292** [comment]
Well, it should not be visually different. But now you can use it, for example, with `d` or `c` commands:
`d` + easymotion search. So, check the list of [supported commands](https://github.com/AlexPl292/IdeaVim-EasyMotion#supported-commands).

**Comment by xbear23** [comment]
> Well, it should not be visually different. But now you can use it, for example, with `d` or `c` commands:
> `d` + easymotion search. So, check the list of [supported commands](https://github.com/AlexPl292/IdeaVim-EasyMotion#supported-commands).

Ok, I get it now, thanks！
