### ISSUE TITLE
ideavim doesn't work.

### ISSUE THREAD

**Issue by kiddoliu** [AlexPl292/IdeaVim-EasyMotion#79]
when I install acejump and ideaVIm-EasyMotion. after restart idea, ideavim doesn't work.

**Comment by kiddoliu** [comment]
plugin screencasts
![image](https://user-images.githubusercontent.com/94882723/171547641-b12a625c-afb4-4d78-a99d-0955c31c4c0a.png)
![image](https://user-images.githubusercontent.com/94882723/171547692-38f6217b-7591-4a46-9812-c99973898c4f.png)
this is my idea.log

[idea.log](https://github.com/AlexPl292/IdeaVim-EasyMotion/files/8820502/idea.log)
this is my plugins screencasts

if I add "Plug 'easymotion/vim-easymotion'" to my ideavimrc
after restart idea, the plugin ideavim does't work. 
![image](https://user-images.githubusercontent.com/94882723/171547903-c61bc72f-f444-4107-9e43-1b20d8287967.png)

**Comment by AlexPl292** [comment]
Hi, it seems like we've released the last version of IdeaVim-EasyMotion with a wrong compatibility range. The new version of the plugin (1.8) is compatible with IJ 2021.3+, but you have 2021.2.
You can either update your version of IJ (and IdeaVim as well), or reinstall the IdeaVim-EasyMotion plugin. After reinstalling the plugin, you should get version 1.7 now.

**Comment by kiddoliu** [comment]
I change the version to 1.7. it has no proplem. 
thank you very much.
IdeaVim-EasyMotion is very usefull.
