### ISSUE TITLE
can Support Chinese 

### ISSUE THREAD

**Issue by ifnk** [AlexPl292/IdeaVim-EasyMotion#8]
like   easymotion-chs [https://github.com/ZSaberLv0/vim-easymotion-chs](url)

Here's a Chinese sentence.
众所周知，中文是没有空格的，要是能有一个插件能支持中文光标跳转就好了！

if you press easymotion-s "z"(The initials of a Chinese character) ，The cursor will jump to "周" “知” “中” “支” front of these characters

![image](https://user-images.githubusercontent.com/39295458/66718380-d104fe00-ee15-11e9-9670-27edfab7dccd.png)

![image](https://user-images.githubusercontent.com/39295458/66718382-d104fe00-ee15-11e9-8385-05bf6ede88b3.png)

And 
Chinese, unlike English, there are no spaces between his words. For example, Chinese "我喜欢你" in English is "i love you", in vim inside, "我喜欢 " is a word, but there are the three words in English and i love and you, so when you press "de","ce" in  vim  it's  will delete the entire sentence, instead of deleting such as "我" or "喜欢" or "你", but English can do this , it  can  deleted "i" or "love" or "you", so can ideavim support Chinese phrase jump? Like the image below this?

![image](https://user-images.githubusercontent.com/39295458/69519964-3c55fa00-0f96-11ea-8a5e-6664d3ec26a3.png)
![image](https://user-images.githubusercontent.com/39295458/69520002-63143080-0f96-11ea-8a9f-66747232d74c.png)

do you use microsoft word? when you input chinese in microsoft word ,if you press "ctrl-<left>" or "ctrl-<right>" ,he will jump like  vim "e" or "b",but he is support chinese jump
![image](https://user-images.githubusercontent.com/39295458/69520667-3a8d3600-0f98-11ea-8ddb-8418177372fb.png)
![image](https://user-images.githubusercontent.com/39295458/69520781-7922f080-0f98-11ea-95db-6efb339b0275.png)

**Comment by AlexPl292** [comment]
@breandan any chance AceJump will support Chinese?

**Comment by breandan** [comment]
Interesting! I will look into it.

**Comment by AlexPl292** [comment]
Starting v3.6.1 AceJump has initial support for Chinese. https://github.com/acejump/AceJump/issues/314#issuecomment-616654905
Since this issue is completely dependent on AceJump, I am closing this issue.
