### ISSUE TITLE
Suddenly stopped working

### ISSUE THREAD

**Issue by codercodingthecode** [AlexPl292/IdeaVim-EasyMotion#87]
I've been using this setup for nearly 2 years with no issues.
Today it stopped working for apparently no reason.
I have tried to re install the ide's. It actually stopped working on all, intelliJ, webstorm, pycharm. [latest stable version]
The basic ideavim commands work, but none easymotion work now.
`LL w, k, l, s`
and I use it A LOT.

I haven't yet detected or able to fix the issue. 
Does anyone have an idea how to go about fixing this?

EDIT:
Adding the configuration manually does nothing as well.

**Comment by AlexPl292** [comment]
Have you filed this issue? https://youtrack.jetbrains.com/issue/VIM-2789
Let's continue the conversation in youtrack.
