### ISSUE TITLE
how does it work

### ISSUE THREAD

**Issue by Skorpionos** [AlexPl292/IdeaVim-EasyMotion#9]
Alex, could you describe more specific, how exactly configure and use your plugin?
I'm sorry, but I just don't understand what means
"Plug (easymotion-f) | <leader><leader>f{char} +  mapped to fn".
Is " Plug " a keymap and where should I set it?

**Comment by AlexPl292** [comment]
Hi! Thank you for the feedback, I'll review the docs.
First of all, you have to follow the [setup](https://github.com/AlexPl292/IdeaVim-EasyMotion#setup) section.
You actually don't have to configure anything specific.
Check out the right column of the first table: `<leader><leader>f{char}` means that you have to press the `<leader>` key twice (it's `\` by default), then `f`, and then the char you like to jump to.
The commands you see on the left side is the name of the command. You can use if you want to map this command to any custom key.
`// mapped to fn` means that in original easymotion this command accepts one char, but in this implementation you can pass several keys (so, it works as `fn` commands).

Actually, this plugin mimics the behavior of [vim-easymotion](https://github.com/easymotion/vim-easymotion#usage-example-for-the-base-features), so you can read their documentation to understand how to work with it.

**Comment by Skorpionos** [comment]
Alex, thank for your answer. Now I begin to understand ). Good idea to integrate with AceJump! 
One more question. Is it possible to configure **EasyMotion** in such way how I asked in https://github.com/acejump/AceJump/issues/299. For example I want to go to next char "=" and I would like to press something like [Alt+F], [=]. I mean like "f" or "t" commands in vim, but it's possible to go to other line.

**Comment by AlexPl292** [comment]
Yes, I see the point, but the only thing I can think about is to search for the symbol with `/`. Looks like the `vim-sneak` plugin can achieve this behavior, but it's not emulated for now.

**Comment by oemergenc** [comment]
I am facing the same problem, any progress on this? I followed the setup instructions, activated all Plugins, inserted `set easymotiion` in `.ideavimrc`, restarted IDE. Still no luck, nothing happens, when invoking `<leader><leader>f{char}` (my leader is also mapped to SPACE).

**Comment by hujianxin** [comment]
@oemergenc Check whether you map `<leader><leader>` to other operations
