### ISSUE TITLE
Easymotions not working in split-tab view

### ISSUE THREAD

**Issue by tanmaychimurkar** [AlexPl292/IdeaVim-EasyMotion#92]
Hi AlexPL292,

Thank you for the amazing plugin to bring EasyMotion to IdeaVim. I have been loving it so far, however, I noticed that when I try to use the plugin after I split right with `:vsp`, and when I start EasyMotion sequence like `<leader>w` on the tab on right, the initial alphabet for the motion appear correctly, however, when I enter the sequence, I suddenly switch back to the other split. I am not sure if this issue is because of my own default keymaps, since I am currently using all the default keymaps provided by PyCharm.

I was not sure if this is normal or a known behavior (I could not find anything related to this in the issues on this repository), and that is why I am reaching out here.

Any help to try to help me figure out this issue with EasyMotion would be very much appreciated.

How to recreate issue: Open two files and split any one of them with `:vsp`. Once in the file on the right pane, try to use EasyMotions like `<leader>w` and then we suddenly switch back to the pane on the left. 

Thanks for the help in advance :)

**Comment by mikravn** [comment]
Hi @tanmaychimurkar


I think that it is due to a bug/regression in AceJump:
https://github.com/acejump/AceJump/issues/417

**Comment by mikravn** [comment]
Issue seems to be resolved when updating to AceJump 3.8.10.
Please update and retest, I suggest to close this ussue.

**Comment by tanmaychimurkar** [comment]
Thanks you for the update. Yes, it seems to be working now. 

Closing issue since it is resolved. Thanks again!
