### ISSUE TITLE
Version 1.10 cause ideavim not working on IDEA 2021.3

### ISSUE THREAD

**Issue by livelazily** [AlexPl292/IdeaVim-EasyMotion#93]
Version 1.9 it was working as normal on IDEA 2021.3
Maybe version 1.10 should update the compatibility range to not support IDEA 2021.3?

**Comment by AlexPl292** [comment]
Hi, thank you for your issue, it was my mistake.
I've updated the minimum version of IJ, please reinstall EasyMotion to get v1.9.
