### ISSUE TITLE
Tags longer than necessary

### ISSUE THREAD

**Issue by bmurauer** [AlexPl292/IdeaVim-EasyMotion#95]
I have used easymotion in vim for a long time, and I noticed that the shortcut tags in the ideavim-version are often longer than the original easymotion.
For example, in this xml file,  the cursor is on line 12 and i trigger `easymotion-bd-jk`, the following tags are shown:
![image](https://user-images.githubusercontent.com/2963032/213395804-2003e500-df15-486b-b87a-6650888477b6.png)

Compared to the same file, cursor position and command opened in vim with regular easymotion:
![image](https://user-images.githubusercontent.com/2963032/213395955-5fa7c845-6960-4ce2-b66e-22282433eea9.png)

The original easymotion seems to allow navigation to closer by lines with one character, and only adds more characters the farther away you want to navigate. Is this something that would be possible for ideavim-easymotion as well?

**Comment by AlexPl292** [comment]
Hi there! The tags are actually provided by acejump plugin and not controlled by IdeaVim-EasyMotion. You can move this ticket there: https://github.com/acejump/AceJump

**Comment by mkrnr** [comment]
Here's a related issue in from the AceJump repo with some suggestions to improve the tags: https://github.com/acejump/AceJump/issues/378
